name: Android Build

on:
  push:
    branches: [ devin/1737084833-implement-mobile-app ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm install
      - name: Build Android APK
        env:
          EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}
          ADMOB_PUBLISHER_ID: ${{ secrets.ADMOB_PUBLISHER_ID }}
          ADMOB_APP_ID: ${{ secrets.ADMOB_APP_ID }}
          ADMOB_BANNER_ID: ${{ secrets.ADMOB_BANNER_ID }}
          ADMOB_REWARDED_ID: ${{ secrets.ADMOB_REWARDED_ID }}
        run: eas build --platform android --profile preview --non-interactive
